name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configurações do Git
      - name: Set up Git
        run: |
          git config --global user.email "AlessandroWindsonMM@gmail.com"
          git config --global user.name "AlessandroWindson"

      # Snake Animation
      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: AlessandroWindson
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Commit changes
      - name: Commit changes
        run: |
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Snake animation"

      # Push changes
      - name: Push changes
        run: git push origin HEAD:main
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
