name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Debug SSH Key
        run: echo "$ACTIONS_DEPLOY_KEY"
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: AlessandroWindson
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

